language: node_js
install: npm install -g gitbook-cli
before_script: gitbook install
node_js:
- '0.10'
script: gitbook build
after_success:
- bash deploy.sh
env:
  global:
    secure: Pvife77THEsfu61tYufmMrvwb6pxaeXJPaXF8kDrl5QM/VdL9d8VoAWuc2hLfzHL/KWrN9nKngATZeHaOwwS+69bSQcW2lptJWARwCyK1g3a5PzS+CX5g3Rpdq0CNDb48f69eD5zssUUvJyNpIJSN/CF/KNTdtycbMAQPfgMSPOuBU77pcnj0GHYpjmwoL1cV9UD/12GS5FWcTUv5EVFQC4kvh7IcRCusVVeQIneE9m/gqTy9TXufmxunBaAXeWw9lDG28RDNGMbo6AJJZZXOhBoE1ahrbt8/M0OlU+TkDIfTtQaIAQINSfQkN+v8ItPAwiBB3Ym0stn99YAVjquposkrTOF+KrrJ90u01bSH/L9AO4Vmf5BC6foxv3XEny0fDbUNO4TxEilU23VRnaD0xBouSgTYP+fjYtPnkngcA7mXZ25kJs4kUXES7w9gViQg0tMVFUNkcapltu5kBR7iX1t9+p72CPMsR2AMZmcM0KxON26nZbUU+I6hdxupPsab01zsISTlZW81tFXlYfzUiVziRJNk5EmfXhB6yrzx3bNRj+RwY9zOXSMg93aosPPNupEbZbTVgevhlRQjm/BvLj7dLyveRjY8/vPHB3KH9hUIkrJ0LwnkLwAmGP4sEBE6TOBKEQpOOmFWSfn3iCWVkD/4ou7j5R+kRLS9Rit83M=